// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cfg.proto
// Protobuf Java Version: 4.27.1

package org.game.proto.struct;

public final class Cfg {
  private Cfg() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Cfg.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbCfgFisheriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbCfgFisheries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne> 
        getAllFisheriesList();
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    org.game.proto.struct.Cfg.PbCfgFisheriesOne getAllFisheries(int index);
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    int getAllFisheriesCount();
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    java.util.List<? extends org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder> 
        getAllFisheriesOrBuilderList();
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder getAllFisheriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbCfgFisheries}
   */
  public static final class PbCfgFisheries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbCfgFisheries)
      PbCfgFisheriesOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbCfgFisheries.class.getName());
    }
    // Use PbCfgFisheries.newBuilder() to construct.
    private PbCfgFisheries(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbCfgFisheries() {
      allFisheries_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Cfg.PbCfgFisheries.class, org.game.proto.struct.Cfg.PbCfgFisheries.Builder.class);
    }

    public static final int ALLFISHERIES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne> allFisheries_;
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne> getAllFisheriesList() {
      return allFisheries_;
    }
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder> 
        getAllFisheriesOrBuilderList() {
      return allFisheries_;
    }
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    @java.lang.Override
    public int getAllFisheriesCount() {
      return allFisheries_.size();
    }
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    @java.lang.Override
    public org.game.proto.struct.Cfg.PbCfgFisheriesOne getAllFisheries(int index) {
      return allFisheries_.get(index);
    }
    /**
     * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
     */
    @java.lang.Override
    public org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder getAllFisheriesOrBuilder(
        int index) {
      return allFisheries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allFisheries_.size(); i++) {
        output.writeMessage(1, allFisheries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allFisheries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allFisheries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Cfg.PbCfgFisheries)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Cfg.PbCfgFisheries other = (org.game.proto.struct.Cfg.PbCfgFisheries) obj;

      if (!getAllFisheriesList()
          .equals(other.getAllFisheriesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllFisheriesCount() > 0) {
        hash = (37 * hash) + ALLFISHERIES_FIELD_NUMBER;
        hash = (53 * hash) + getAllFisheriesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Cfg.PbCfgFisheries prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbCfgFisheries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbCfgFisheries)
        org.game.proto.struct.Cfg.PbCfgFisheriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheries_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Cfg.PbCfgFisheries.class, org.game.proto.struct.Cfg.PbCfgFisheries.Builder.class);
      }

      // Construct using org.game.proto.struct.Cfg.PbCfgFisheries.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (allFisheriesBuilder_ == null) {
          allFisheries_ = java.util.Collections.emptyList();
        } else {
          allFisheries_ = null;
          allFisheriesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheries_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheries getDefaultInstanceForType() {
        return org.game.proto.struct.Cfg.PbCfgFisheries.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheries build() {
        org.game.proto.struct.Cfg.PbCfgFisheries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheries buildPartial() {
        org.game.proto.struct.Cfg.PbCfgFisheries result = new org.game.proto.struct.Cfg.PbCfgFisheries(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.game.proto.struct.Cfg.PbCfgFisheries result) {
        if (allFisheriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            allFisheries_ = java.util.Collections.unmodifiableList(allFisheries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allFisheries_ = allFisheries_;
        } else {
          result.allFisheries_ = allFisheriesBuilder_.build();
        }
      }

      private void buildPartial0(org.game.proto.struct.Cfg.PbCfgFisheries result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Cfg.PbCfgFisheries) {
          return mergeFrom((org.game.proto.struct.Cfg.PbCfgFisheries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Cfg.PbCfgFisheries other) {
        if (other == org.game.proto.struct.Cfg.PbCfgFisheries.getDefaultInstance()) return this;
        if (allFisheriesBuilder_ == null) {
          if (!other.allFisheries_.isEmpty()) {
            if (allFisheries_.isEmpty()) {
              allFisheries_ = other.allFisheries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllFisheriesIsMutable();
              allFisheries_.addAll(other.allFisheries_);
            }
            onChanged();
          }
        } else {
          if (!other.allFisheries_.isEmpty()) {
            if (allFisheriesBuilder_.isEmpty()) {
              allFisheriesBuilder_.dispose();
              allFisheriesBuilder_ = null;
              allFisheries_ = other.allFisheries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allFisheriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAllFisheriesFieldBuilder() : null;
            } else {
              allFisheriesBuilder_.addAllMessages(other.allFisheries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.game.proto.struct.Cfg.PbCfgFisheriesOne m =
                    input.readMessage(
                        org.game.proto.struct.Cfg.PbCfgFisheriesOne.parser(),
                        extensionRegistry);
                if (allFisheriesBuilder_ == null) {
                  ensureAllFisheriesIsMutable();
                  allFisheries_.add(m);
                } else {
                  allFisheriesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne> allFisheries_ =
        java.util.Collections.emptyList();
      private void ensureAllFisheriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          allFisheries_ = new java.util.ArrayList<org.game.proto.struct.Cfg.PbCfgFisheriesOne>(allFisheries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.proto.struct.Cfg.PbCfgFisheriesOne, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder, org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder> allFisheriesBuilder_;

      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne> getAllFisheriesList() {
        if (allFisheriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allFisheries_);
        } else {
          return allFisheriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public int getAllFisheriesCount() {
        if (allFisheriesBuilder_ == null) {
          return allFisheries_.size();
        } else {
          return allFisheriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne getAllFisheries(int index) {
        if (allFisheriesBuilder_ == null) {
          return allFisheries_.get(index);
        } else {
          return allFisheriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder setAllFisheries(
          int index, org.game.proto.struct.Cfg.PbCfgFisheriesOne value) {
        if (allFisheriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllFisheriesIsMutable();
          allFisheries_.set(index, value);
          onChanged();
        } else {
          allFisheriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder setAllFisheries(
          int index, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder builderForValue) {
        if (allFisheriesBuilder_ == null) {
          ensureAllFisheriesIsMutable();
          allFisheries_.set(index, builderForValue.build());
          onChanged();
        } else {
          allFisheriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder addAllFisheries(org.game.proto.struct.Cfg.PbCfgFisheriesOne value) {
        if (allFisheriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllFisheriesIsMutable();
          allFisheries_.add(value);
          onChanged();
        } else {
          allFisheriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder addAllFisheries(
          int index, org.game.proto.struct.Cfg.PbCfgFisheriesOne value) {
        if (allFisheriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllFisheriesIsMutable();
          allFisheries_.add(index, value);
          onChanged();
        } else {
          allFisheriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder addAllFisheries(
          org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder builderForValue) {
        if (allFisheriesBuilder_ == null) {
          ensureAllFisheriesIsMutable();
          allFisheries_.add(builderForValue.build());
          onChanged();
        } else {
          allFisheriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder addAllFisheries(
          int index, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder builderForValue) {
        if (allFisheriesBuilder_ == null) {
          ensureAllFisheriesIsMutable();
          allFisheries_.add(index, builderForValue.build());
          onChanged();
        } else {
          allFisheriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder addAllAllFisheries(
          java.lang.Iterable<? extends org.game.proto.struct.Cfg.PbCfgFisheriesOne> values) {
        if (allFisheriesBuilder_ == null) {
          ensureAllFisheriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allFisheries_);
          onChanged();
        } else {
          allFisheriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder clearAllFisheries() {
        if (allFisheriesBuilder_ == null) {
          allFisheries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allFisheriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public Builder removeAllFisheries(int index) {
        if (allFisheriesBuilder_ == null) {
          ensureAllFisheriesIsMutable();
          allFisheries_.remove(index);
          onChanged();
        } else {
          allFisheriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder getAllFisheriesBuilder(
          int index) {
        return getAllFisheriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder getAllFisheriesOrBuilder(
          int index) {
        if (allFisheriesBuilder_ == null) {
          return allFisheries_.get(index);  } else {
          return allFisheriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public java.util.List<? extends org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder> 
           getAllFisheriesOrBuilderList() {
        if (allFisheriesBuilder_ != null) {
          return allFisheriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allFisheries_);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder addAllFisheriesBuilder() {
        return getAllFisheriesFieldBuilder().addBuilder(
            org.game.proto.struct.Cfg.PbCfgFisheriesOne.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder addAllFisheriesBuilder(
          int index) {
        return getAllFisheriesFieldBuilder().addBuilder(
            index, org.game.proto.struct.Cfg.PbCfgFisheriesOne.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.proto.struct.PbCfgFisheriesOne allFisheries = 1;</code>
       */
      public java.util.List<org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder> 
           getAllFisheriesBuilderList() {
        return getAllFisheriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.proto.struct.Cfg.PbCfgFisheriesOne, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder, org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder> 
          getAllFisheriesFieldBuilder() {
        if (allFisheriesBuilder_ == null) {
          allFisheriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.game.proto.struct.Cfg.PbCfgFisheriesOne, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder, org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder>(
                  allFisheries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          allFisheries_ = null;
        }
        return allFisheriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbCfgFisheries)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbCfgFisheries)
    private static final org.game.proto.struct.Cfg.PbCfgFisheries DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Cfg.PbCfgFisheries();
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheries getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbCfgFisheries>
        PARSER = new com.google.protobuf.AbstractParser<PbCfgFisheries>() {
      @java.lang.Override
      public PbCfgFisheries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbCfgFisheries> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbCfgFisheries> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Cfg.PbCfgFisheries getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbCfgFisheriesOneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbCfgFisheriesOne)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 direction = 2;</code>
     * @return The direction.
     */
    int getDirection();

    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    java.util.List<org.game.proto.struct.Cfg.PbFishInfo> 
        getFishesList();
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    org.game.proto.struct.Cfg.PbFishInfo getFishes(int index);
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    int getFishesCount();
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    java.util.List<? extends org.game.proto.struct.Cfg.PbFishInfoOrBuilder> 
        getFishesOrBuilderList();
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    org.game.proto.struct.Cfg.PbFishInfoOrBuilder getFishesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbCfgFisheriesOne}
   */
  public static final class PbCfgFisheriesOne extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbCfgFisheriesOne)
      PbCfgFisheriesOneOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbCfgFisheriesOne.class.getName());
    }
    // Use PbCfgFisheriesOne.newBuilder() to construct.
    private PbCfgFisheriesOne(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbCfgFisheriesOne() {
      id_ = "";
      fishes_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheriesOne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Cfg.PbCfgFisheriesOne.class, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private int direction_ = 0;
    /**
     * <code>int32 direction = 2;</code>
     * @return The direction.
     */
    @java.lang.Override
    public int getDirection() {
      return direction_;
    }

    public static final int FISHES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<org.game.proto.struct.Cfg.PbFishInfo> fishes_;
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.game.proto.struct.Cfg.PbFishInfo> getFishesList() {
      return fishes_;
    }
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.game.proto.struct.Cfg.PbFishInfoOrBuilder> 
        getFishesOrBuilderList() {
      return fishes_;
    }
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    @java.lang.Override
    public int getFishesCount() {
      return fishes_.size();
    }
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    @java.lang.Override
    public org.game.proto.struct.Cfg.PbFishInfo getFishes(int index) {
      return fishes_.get(index);
    }
    /**
     * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
     */
    @java.lang.Override
    public org.game.proto.struct.Cfg.PbFishInfoOrBuilder getFishesOrBuilder(
        int index) {
      return fishes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (direction_ != 0) {
        output.writeInt32(2, direction_);
      }
      for (int i = 0; i < fishes_.size(); i++) {
        output.writeMessage(3, fishes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (direction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, direction_);
      }
      for (int i = 0; i < fishes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, fishes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Cfg.PbCfgFisheriesOne)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Cfg.PbCfgFisheriesOne other = (org.game.proto.struct.Cfg.PbCfgFisheriesOne) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getDirection()
          != other.getDirection()) return false;
      if (!getFishesList()
          .equals(other.getFishesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection();
      if (getFishesCount() > 0) {
        hash = (37 * hash) + FISHES_FIELD_NUMBER;
        hash = (53 * hash) + getFishesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Cfg.PbCfgFisheriesOne prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbCfgFisheriesOne}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbCfgFisheriesOne)
        org.game.proto.struct.Cfg.PbCfgFisheriesOneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheriesOne_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Cfg.PbCfgFisheriesOne.class, org.game.proto.struct.Cfg.PbCfgFisheriesOne.Builder.class);
      }

      // Construct using org.game.proto.struct.Cfg.PbCfgFisheriesOne.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        direction_ = 0;
        if (fishesBuilder_ == null) {
          fishes_ = java.util.Collections.emptyList();
        } else {
          fishes_ = null;
          fishesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne getDefaultInstanceForType() {
        return org.game.proto.struct.Cfg.PbCfgFisheriesOne.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne build() {
        org.game.proto.struct.Cfg.PbCfgFisheriesOne result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbCfgFisheriesOne buildPartial() {
        org.game.proto.struct.Cfg.PbCfgFisheriesOne result = new org.game.proto.struct.Cfg.PbCfgFisheriesOne(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.game.proto.struct.Cfg.PbCfgFisheriesOne result) {
        if (fishesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            fishes_ = java.util.Collections.unmodifiableList(fishes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.fishes_ = fishes_;
        } else {
          result.fishes_ = fishesBuilder_.build();
        }
      }

      private void buildPartial0(org.game.proto.struct.Cfg.PbCfgFisheriesOne result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.direction_ = direction_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Cfg.PbCfgFisheriesOne) {
          return mergeFrom((org.game.proto.struct.Cfg.PbCfgFisheriesOne)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Cfg.PbCfgFisheriesOne other) {
        if (other == org.game.proto.struct.Cfg.PbCfgFisheriesOne.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDirection() != 0) {
          setDirection(other.getDirection());
        }
        if (fishesBuilder_ == null) {
          if (!other.fishes_.isEmpty()) {
            if (fishes_.isEmpty()) {
              fishes_ = other.fishes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureFishesIsMutable();
              fishes_.addAll(other.fishes_);
            }
            onChanged();
          }
        } else {
          if (!other.fishes_.isEmpty()) {
            if (fishesBuilder_.isEmpty()) {
              fishesBuilder_.dispose();
              fishesBuilder_ = null;
              fishes_ = other.fishes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              fishesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFishesFieldBuilder() : null;
            } else {
              fishesBuilder_.addAllMessages(other.fishes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                direction_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                org.game.proto.struct.Cfg.PbFishInfo m =
                    input.readMessage(
                        org.game.proto.struct.Cfg.PbFishInfo.parser(),
                        extensionRegistry);
                if (fishesBuilder_ == null) {
                  ensureFishesIsMutable();
                  fishes_.add(m);
                } else {
                  fishesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int direction_ ;
      /**
       * <code>int32 direction = 2;</code>
       * @return The direction.
       */
      @java.lang.Override
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>int32 direction = 2;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(int value) {

        direction_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 direction = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000002);
        direction_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<org.game.proto.struct.Cfg.PbFishInfo> fishes_ =
        java.util.Collections.emptyList();
      private void ensureFishesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          fishes_ = new java.util.ArrayList<org.game.proto.struct.Cfg.PbFishInfo>(fishes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.proto.struct.Cfg.PbFishInfo, org.game.proto.struct.Cfg.PbFishInfo.Builder, org.game.proto.struct.Cfg.PbFishInfoOrBuilder> fishesBuilder_;

      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public java.util.List<org.game.proto.struct.Cfg.PbFishInfo> getFishesList() {
        if (fishesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fishes_);
        } else {
          return fishesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public int getFishesCount() {
        if (fishesBuilder_ == null) {
          return fishes_.size();
        } else {
          return fishesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public org.game.proto.struct.Cfg.PbFishInfo getFishes(int index) {
        if (fishesBuilder_ == null) {
          return fishes_.get(index);
        } else {
          return fishesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder setFishes(
          int index, org.game.proto.struct.Cfg.PbFishInfo value) {
        if (fishesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishesIsMutable();
          fishes_.set(index, value);
          onChanged();
        } else {
          fishesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder setFishes(
          int index, org.game.proto.struct.Cfg.PbFishInfo.Builder builderForValue) {
        if (fishesBuilder_ == null) {
          ensureFishesIsMutable();
          fishes_.set(index, builderForValue.build());
          onChanged();
        } else {
          fishesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder addFishes(org.game.proto.struct.Cfg.PbFishInfo value) {
        if (fishesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishesIsMutable();
          fishes_.add(value);
          onChanged();
        } else {
          fishesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder addFishes(
          int index, org.game.proto.struct.Cfg.PbFishInfo value) {
        if (fishesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishesIsMutable();
          fishes_.add(index, value);
          onChanged();
        } else {
          fishesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder addFishes(
          org.game.proto.struct.Cfg.PbFishInfo.Builder builderForValue) {
        if (fishesBuilder_ == null) {
          ensureFishesIsMutable();
          fishes_.add(builderForValue.build());
          onChanged();
        } else {
          fishesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder addFishes(
          int index, org.game.proto.struct.Cfg.PbFishInfo.Builder builderForValue) {
        if (fishesBuilder_ == null) {
          ensureFishesIsMutable();
          fishes_.add(index, builderForValue.build());
          onChanged();
        } else {
          fishesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder addAllFishes(
          java.lang.Iterable<? extends org.game.proto.struct.Cfg.PbFishInfo> values) {
        if (fishesBuilder_ == null) {
          ensureFishesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fishes_);
          onChanged();
        } else {
          fishesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder clearFishes() {
        if (fishesBuilder_ == null) {
          fishes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          fishesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public Builder removeFishes(int index) {
        if (fishesBuilder_ == null) {
          ensureFishesIsMutable();
          fishes_.remove(index);
          onChanged();
        } else {
          fishesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public org.game.proto.struct.Cfg.PbFishInfo.Builder getFishesBuilder(
          int index) {
        return getFishesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public org.game.proto.struct.Cfg.PbFishInfoOrBuilder getFishesOrBuilder(
          int index) {
        if (fishesBuilder_ == null) {
          return fishes_.get(index);  } else {
          return fishesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public java.util.List<? extends org.game.proto.struct.Cfg.PbFishInfoOrBuilder> 
           getFishesOrBuilderList() {
        if (fishesBuilder_ != null) {
          return fishesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fishes_);
        }
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public org.game.proto.struct.Cfg.PbFishInfo.Builder addFishesBuilder() {
        return getFishesFieldBuilder().addBuilder(
            org.game.proto.struct.Cfg.PbFishInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public org.game.proto.struct.Cfg.PbFishInfo.Builder addFishesBuilder(
          int index) {
        return getFishesFieldBuilder().addBuilder(
            index, org.game.proto.struct.Cfg.PbFishInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.proto.struct.PbFishInfo fishes = 3;</code>
       */
      public java.util.List<org.game.proto.struct.Cfg.PbFishInfo.Builder> 
           getFishesBuilderList() {
        return getFishesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.proto.struct.Cfg.PbFishInfo, org.game.proto.struct.Cfg.PbFishInfo.Builder, org.game.proto.struct.Cfg.PbFishInfoOrBuilder> 
          getFishesFieldBuilder() {
        if (fishesBuilder_ == null) {
          fishesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.game.proto.struct.Cfg.PbFishInfo, org.game.proto.struct.Cfg.PbFishInfo.Builder, org.game.proto.struct.Cfg.PbFishInfoOrBuilder>(
                  fishes_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          fishes_ = null;
        }
        return fishesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbCfgFisheriesOne)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbCfgFisheriesOne)
    private static final org.game.proto.struct.Cfg.PbCfgFisheriesOne DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Cfg.PbCfgFisheriesOne();
    }

    public static org.game.proto.struct.Cfg.PbCfgFisheriesOne getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbCfgFisheriesOne>
        PARSER = new com.google.protobuf.AbstractParser<PbCfgFisheriesOne>() {
      @java.lang.Override
      public PbCfgFisheriesOne parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbCfgFisheriesOne> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbCfgFisheriesOne> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Cfg.PbCfgFisheriesOne getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbFishInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbFishInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 fishTempId = 1;</code>
     * @return The fishTempId.
     */
    int getFishTempId();

    /**
     * <code>double endTime = 2;</code>
     * @return The endTime.
     */
    double getEndTime();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbFishInfo}
   */
  public static final class PbFishInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbFishInfo)
      PbFishInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbFishInfo.class.getName());
    }
    // Use PbFishInfo.newBuilder() to construct.
    private PbFishInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbFishInfo() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbFishInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbFishInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Cfg.PbFishInfo.class, org.game.proto.struct.Cfg.PbFishInfo.Builder.class);
    }

    public static final int FISHTEMPID_FIELD_NUMBER = 1;
    private int fishTempId_ = 0;
    /**
     * <code>int32 fishTempId = 1;</code>
     * @return The fishTempId.
     */
    @java.lang.Override
    public int getFishTempId() {
      return fishTempId_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private double endTime_ = 0D;
    /**
     * <code>double endTime = 2;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public double getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fishTempId_ != 0) {
        output.writeInt32(1, fishTempId_);
      }
      if (java.lang.Double.doubleToRawLongBits(endTime_) != 0) {
        output.writeDouble(2, endTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fishTempId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fishTempId_);
      }
      if (java.lang.Double.doubleToRawLongBits(endTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Cfg.PbFishInfo)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Cfg.PbFishInfo other = (org.game.proto.struct.Cfg.PbFishInfo) obj;

      if (getFishTempId()
          != other.getFishTempId()) return false;
      if (java.lang.Double.doubleToLongBits(getEndTime())
          != java.lang.Double.doubleToLongBits(
              other.getEndTime())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FISHTEMPID_FIELD_NUMBER;
      hash = (53 * hash) + getFishTempId();
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getEndTime()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Cfg.PbFishInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Cfg.PbFishInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Cfg.PbFishInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Cfg.PbFishInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbFishInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbFishInfo)
        org.game.proto.struct.Cfg.PbFishInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbFishInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbFishInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Cfg.PbFishInfo.class, org.game.proto.struct.Cfg.PbFishInfo.Builder.class);
      }

      // Construct using org.game.proto.struct.Cfg.PbFishInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fishTempId_ = 0;
        endTime_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Cfg.internal_static_org_game_proto_struct_PbFishInfo_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbFishInfo getDefaultInstanceForType() {
        return org.game.proto.struct.Cfg.PbFishInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbFishInfo build() {
        org.game.proto.struct.Cfg.PbFishInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Cfg.PbFishInfo buildPartial() {
        org.game.proto.struct.Cfg.PbFishInfo result = new org.game.proto.struct.Cfg.PbFishInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Cfg.PbFishInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fishTempId_ = fishTempId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.endTime_ = endTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Cfg.PbFishInfo) {
          return mergeFrom((org.game.proto.struct.Cfg.PbFishInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Cfg.PbFishInfo other) {
        if (other == org.game.proto.struct.Cfg.PbFishInfo.getDefaultInstance()) return this;
        if (other.getFishTempId() != 0) {
          setFishTempId(other.getFishTempId());
        }
        if (other.getEndTime() != 0D) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                fishTempId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                endTime_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int fishTempId_ ;
      /**
       * <code>int32 fishTempId = 1;</code>
       * @return The fishTempId.
       */
      @java.lang.Override
      public int getFishTempId() {
        return fishTempId_;
      }
      /**
       * <code>int32 fishTempId = 1;</code>
       * @param value The fishTempId to set.
       * @return This builder for chaining.
       */
      public Builder setFishTempId(int value) {

        fishTempId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fishTempId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFishTempId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fishTempId_ = 0;
        onChanged();
        return this;
      }

      private double endTime_ ;
      /**
       * <code>double endTime = 2;</code>
       * @return The endTime.
       */
      @java.lang.Override
      public double getEndTime() {
        return endTime_;
      }
      /**
       * <code>double endTime = 2;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(double value) {

        endTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double endTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbFishInfo)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbFishInfo)
    private static final org.game.proto.struct.Cfg.PbFishInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Cfg.PbFishInfo();
    }

    public static org.game.proto.struct.Cfg.PbFishInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbFishInfo>
        PARSER = new com.google.protobuf.AbstractParser<PbFishInfo>() {
      @java.lang.Override
      public PbFishInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbFishInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbFishInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Cfg.PbFishInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbCfgFisheries_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbCfgFisheries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbCfgFisheriesOne_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbFishInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbFishInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcfg.proto\022\025org.game.proto.struct\"P\n\016Pb" +
      "CfgFisheries\022>\n\014allFisheries\030\001 \003(\0132(.org" +
      ".game.proto.struct.PbCfgFisheriesOne\"e\n\021" +
      "PbCfgFisheriesOne\022\n\n\002id\030\001 \001(\t\022\021\n\tdirecti" +
      "on\030\002 \001(\005\0221\n\006fishes\030\003 \003(\0132!.org.game.prot" +
      "o.struct.PbFishInfo\"1\n\nPbFishInfo\022\022\n\nfis" +
      "hTempId\030\001 \001(\005\022\017\n\007endTime\030\002 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_game_proto_struct_PbCfgFisheries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_game_proto_struct_PbCfgFisheries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbCfgFisheries_descriptor,
        new java.lang.String[] { "AllFisheries", });
    internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_game_proto_struct_PbCfgFisheriesOne_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbCfgFisheriesOne_descriptor,
        new java.lang.String[] { "Id", "Direction", "Fishes", });
    internal_static_org_game_proto_struct_PbFishInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_game_proto_struct_PbFishInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbFishInfo_descriptor,
        new java.lang.String[] { "FishTempId", "EndTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
