// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.27.1

package org.game.proto.struct;

public final class Common {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Common.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 val = 1;</code>
     * @return The val.
     */
    int getVal();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbInt}
   */
  public static final class PbInt extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbInt)
      PbIntOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbInt.class.getName());
    }
    // Use PbInt.newBuilder() to construct.
    private PbInt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbInt() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbInt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Common.PbInt.class, org.game.proto.struct.Common.PbInt.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    private int val_ = 0;
    /**
     * <code>int32 val = 1;</code>
     * @return The val.
     */
    @java.lang.Override
    public int getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (val_ != 0) {
        output.writeInt32(1, val_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (val_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Common.PbInt)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Common.PbInt other = (org.game.proto.struct.Common.PbInt) obj;

      if (getVal()
          != other.getVal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + getVal();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Common.PbInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Common.PbInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Common.PbInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Common.PbInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbInt)
        org.game.proto.struct.Common.PbIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbInt_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Common.PbInt.class, org.game.proto.struct.Common.PbInt.Builder.class);
      }

      // Construct using org.game.proto.struct.Common.PbInt.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        val_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbInt_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbInt getDefaultInstanceForType() {
        return org.game.proto.struct.Common.PbInt.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbInt build() {
        org.game.proto.struct.Common.PbInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbInt buildPartial() {
        org.game.proto.struct.Common.PbInt result = new org.game.proto.struct.Common.PbInt(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Common.PbInt result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.val_ = val_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Common.PbInt) {
          return mergeFrom((org.game.proto.struct.Common.PbInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Common.PbInt other) {
        if (other == org.game.proto.struct.Common.PbInt.getDefaultInstance()) return this;
        if (other.getVal() != 0) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                val_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int val_ ;
      /**
       * <code>int32 val = 1;</code>
       * @return The val.
       */
      @java.lang.Override
      public int getVal() {
        return val_;
      }
      /**
       * <code>int32 val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(int value) {

        val_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbInt)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbInt)
    private static final org.game.proto.struct.Common.PbInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Common.PbInt();
    }

    public static org.game.proto.struct.Common.PbInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbInt>
        PARSER = new com.google.protobuf.AbstractParser<PbInt>() {
      @java.lang.Override
      public PbInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbInt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbInt> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Common.PbInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string val = 1;</code>
     * @return The val.
     */
    java.lang.String getVal();
    /**
     * <code>string val = 1;</code>
     * @return The bytes for val.
     */
    com.google.protobuf.ByteString
        getValBytes();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbString}
   */
  public static final class PbString extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbString)
      PbStringOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbString.class.getName());
    }
    // Use PbString.newBuilder() to construct.
    private PbString(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbString() {
      val_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbString_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Common.PbString.class, org.game.proto.struct.Common.PbString.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object val_ = "";
    /**
     * <code>string val = 1;</code>
     * @return The val.
     */
    @java.lang.Override
    public java.lang.String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val_ = s;
        return s;
      }
    }
    /**
     * <code>string val = 1;</code>
     * @return The bytes for val.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(val_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, val_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(val_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, val_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Common.PbString)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Common.PbString other = (org.game.proto.struct.Common.PbString) obj;

      if (!getVal()
          .equals(other.getVal())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + getVal().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Common.PbString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Common.PbString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Common.PbString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Common.PbString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbString)
        org.game.proto.struct.Common.PbStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbString_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Common.PbString.class, org.game.proto.struct.Common.PbString.Builder.class);
      }

      // Construct using org.game.proto.struct.Common.PbString.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        val_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbString_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbString getDefaultInstanceForType() {
        return org.game.proto.struct.Common.PbString.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbString build() {
        org.game.proto.struct.Common.PbString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbString buildPartial() {
        org.game.proto.struct.Common.PbString result = new org.game.proto.struct.Common.PbString(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Common.PbString result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.val_ = val_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Common.PbString) {
          return mergeFrom((org.game.proto.struct.Common.PbString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Common.PbString other) {
        if (other == org.game.proto.struct.Common.PbString.getDefaultInstance()) return this;
        if (!other.getVal().isEmpty()) {
          val_ = other.val_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                val_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object val_ = "";
      /**
       * <code>string val = 1;</code>
       * @return The val.
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          val_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string val = 1;</code>
       * @return The bytes for val.
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        val_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        val_ = getDefaultInstance().getVal();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string val = 1;</code>
       * @param value The bytes for val to set.
       * @return This builder for chaining.
       */
      public Builder setValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        val_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbString)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbString)
    private static final org.game.proto.struct.Common.PbString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Common.PbString();
    }

    public static org.game.proto.struct.Common.PbString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbString>
        PARSER = new com.google.protobuf.AbstractParser<PbString>() {
      @java.lang.Override
      public PbString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbString> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Common.PbString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbLongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbLong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 val = 1;</code>
     * @return The val.
     */
    long getVal();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbLong}
   */
  public static final class PbLong extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbLong)
      PbLongOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbLong.class.getName());
    }
    // Use PbLong.newBuilder() to construct.
    private PbLong(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbLong() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbLong_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbLong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Common.PbLong.class, org.game.proto.struct.Common.PbLong.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    private long val_ = 0L;
    /**
     * <code>int64 val = 1;</code>
     * @return The val.
     */
    @java.lang.Override
    public long getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (val_ != 0L) {
        output.writeInt64(1, val_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (val_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, val_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Common.PbLong)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Common.PbLong other = (org.game.proto.struct.Common.PbLong) obj;

      if (getVal()
          != other.getVal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVal());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Common.PbLong parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Common.PbLong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Common.PbLong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbLong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Common.PbLong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbLong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbLong)
        org.game.proto.struct.Common.PbLongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbLong_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbLong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Common.PbLong.class, org.game.proto.struct.Common.PbLong.Builder.class);
      }

      // Construct using org.game.proto.struct.Common.PbLong.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        val_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbLong_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbLong getDefaultInstanceForType() {
        return org.game.proto.struct.Common.PbLong.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbLong build() {
        org.game.proto.struct.Common.PbLong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbLong buildPartial() {
        org.game.proto.struct.Common.PbLong result = new org.game.proto.struct.Common.PbLong(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Common.PbLong result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.val_ = val_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Common.PbLong) {
          return mergeFrom((org.game.proto.struct.Common.PbLong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Common.PbLong other) {
        if (other == org.game.proto.struct.Common.PbLong.getDefaultInstance()) return this;
        if (other.getVal() != 0L) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                val_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long val_ ;
      /**
       * <code>int64 val = 1;</code>
       * @return The val.
       */
      @java.lang.Override
      public long getVal() {
        return val_;
      }
      /**
       * <code>int64 val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(long value) {

        val_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbLong)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbLong)
    private static final org.game.proto.struct.Common.PbLong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Common.PbLong();
    }

    public static org.game.proto.struct.Common.PbLong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbLong>
        PARSER = new com.google.protobuf.AbstractParser<PbLong>() {
      @java.lang.Override
      public PbLong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbLong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbLong> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Common.PbLong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbBoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbBool)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool val = 1;</code>
     * @return The val.
     */
    boolean getVal();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbBool}
   */
  public static final class PbBool extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbBool)
      PbBoolOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        PbBool.class.getName());
    }
    // Use PbBool.newBuilder() to construct.
    private PbBool(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbBool() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbBool_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbBool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Common.PbBool.class, org.game.proto.struct.Common.PbBool.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    private boolean val_ = false;
    /**
     * <code>bool val = 1;</code>
     * @return The val.
     */
    @java.lang.Override
    public boolean getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (val_ != false) {
        output.writeBool(1, val_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (val_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, val_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Common.PbBool)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Common.PbBool other = (org.game.proto.struct.Common.PbBool) obj;

      if (getVal()
          != other.getVal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVal());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Common.PbBool parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Common.PbBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Common.PbBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Common.PbBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Common.PbBool prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbBool}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbBool)
        org.game.proto.struct.Common.PbBoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbBool_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbBool_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Common.PbBool.class, org.game.proto.struct.Common.PbBool.Builder.class);
      }

      // Construct using org.game.proto.struct.Common.PbBool.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        val_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Common.internal_static_org_game_proto_struct_PbBool_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbBool getDefaultInstanceForType() {
        return org.game.proto.struct.Common.PbBool.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbBool build() {
        org.game.proto.struct.Common.PbBool result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Common.PbBool buildPartial() {
        org.game.proto.struct.Common.PbBool result = new org.game.proto.struct.Common.PbBool(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Common.PbBool result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.val_ = val_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Common.PbBool) {
          return mergeFrom((org.game.proto.struct.Common.PbBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Common.PbBool other) {
        if (other == org.game.proto.struct.Common.PbBool.getDefaultInstance()) return this;
        if (other.getVal() != false) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                val_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean val_ ;
      /**
       * <code>bool val = 1;</code>
       * @return The val.
       */
      @java.lang.Override
      public boolean getVal() {
        return val_;
      }
      /**
       * <code>bool val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(boolean value) {

        val_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbBool)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbBool)
    private static final org.game.proto.struct.Common.PbBool DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Common.PbBool();
    }

    public static org.game.proto.struct.Common.PbBool getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbBool>
        PARSER = new com.google.protobuf.AbstractParser<PbBool>() {
      @java.lang.Override
      public PbBool parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbBool> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbBool> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Common.PbBool getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbInt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbString_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbLong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbLong_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbBool_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbBool_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\025org.game.proto.struct\"\024\n" +
      "\005PbInt\022\013\n\003val\030\001 \001(\005\"\027\n\010PbString\022\013\n\003val\030\001" +
      " \001(\t\"\025\n\006PbLong\022\013\n\003val\030\001 \001(\003\"\025\n\006PbBool\022\013\n" +
      "\003val\030\001 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_game_proto_struct_PbInt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_game_proto_struct_PbInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbInt_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_org_game_proto_struct_PbString_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_game_proto_struct_PbString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbString_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_org_game_proto_struct_PbLong_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_game_proto_struct_PbLong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbLong_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_org_game_proto_struct_PbBool_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_game_proto_struct_PbBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbBool_descriptor,
        new java.lang.String[] { "Val", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
