// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: system.proto
// Protobuf Java Version: 4.29.3

package org.game.proto.struct;

public final class System {
  private System() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      System.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbGetServerTimeRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbGetServerTimeResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前毫秒时间戳
     * </pre>
     *
     * <code>int64 currentTimeMillis = 1;</code>
     * @return The currentTimeMillis.
     */
    long getCurrentTimeMillis();
  }
  /**
   * <pre>
   * 返回服务器时间
   * </pre>
   *
   * Protobuf type {@code org.game.proto.struct.PbGetServerTimeResp}
   */
  public static final class PbGetServerTimeResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbGetServerTimeResp)
      PbGetServerTimeRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        PbGetServerTimeResp.class.getName());
    }
    // Use PbGetServerTimeResp.newBuilder() to construct.
    private PbGetServerTimeResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbGetServerTimeResp() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.System.internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.System.internal_static_org_game_proto_struct_PbGetServerTimeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.System.PbGetServerTimeResp.class, org.game.proto.struct.System.PbGetServerTimeResp.Builder.class);
    }

    public static final int CURRENTTIMEMILLIS_FIELD_NUMBER = 1;
    private long currentTimeMillis_ = 0L;
    /**
     * <pre>
     * 当前毫秒时间戳
     * </pre>
     *
     * <code>int64 currentTimeMillis = 1;</code>
     * @return The currentTimeMillis.
     */
    @java.lang.Override
    public long getCurrentTimeMillis() {
      return currentTimeMillis_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currentTimeMillis_ != 0L) {
        output.writeInt64(1, currentTimeMillis_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currentTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, currentTimeMillis_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.System.PbGetServerTimeResp)) {
        return super.equals(obj);
      }
      org.game.proto.struct.System.PbGetServerTimeResp other = (org.game.proto.struct.System.PbGetServerTimeResp) obj;

      if (getCurrentTimeMillis()
          != other.getCurrentTimeMillis()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTTIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentTimeMillis());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.System.PbGetServerTimeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.System.PbGetServerTimeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.System.PbGetServerTimeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.System.PbGetServerTimeResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回服务器时间
     * </pre>
     *
     * Protobuf type {@code org.game.proto.struct.PbGetServerTimeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbGetServerTimeResp)
        org.game.proto.struct.System.PbGetServerTimeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.System.internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.System.internal_static_org_game_proto_struct_PbGetServerTimeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.System.PbGetServerTimeResp.class, org.game.proto.struct.System.PbGetServerTimeResp.Builder.class);
      }

      // Construct using org.game.proto.struct.System.PbGetServerTimeResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        currentTimeMillis_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.System.internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.System.PbGetServerTimeResp getDefaultInstanceForType() {
        return org.game.proto.struct.System.PbGetServerTimeResp.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.System.PbGetServerTimeResp build() {
        org.game.proto.struct.System.PbGetServerTimeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.System.PbGetServerTimeResp buildPartial() {
        org.game.proto.struct.System.PbGetServerTimeResp result = new org.game.proto.struct.System.PbGetServerTimeResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.System.PbGetServerTimeResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.currentTimeMillis_ = currentTimeMillis_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.System.PbGetServerTimeResp) {
          return mergeFrom((org.game.proto.struct.System.PbGetServerTimeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.System.PbGetServerTimeResp other) {
        if (other == org.game.proto.struct.System.PbGetServerTimeResp.getDefaultInstance()) return this;
        if (other.getCurrentTimeMillis() != 0L) {
          setCurrentTimeMillis(other.getCurrentTimeMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                currentTimeMillis_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long currentTimeMillis_ ;
      /**
       * <pre>
       * 当前毫秒时间戳
       * </pre>
       *
       * <code>int64 currentTimeMillis = 1;</code>
       * @return The currentTimeMillis.
       */
      @java.lang.Override
      public long getCurrentTimeMillis() {
        return currentTimeMillis_;
      }
      /**
       * <pre>
       * 当前毫秒时间戳
       * </pre>
       *
       * <code>int64 currentTimeMillis = 1;</code>
       * @param value The currentTimeMillis to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTimeMillis(long value) {

        currentTimeMillis_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前毫秒时间戳
       * </pre>
       *
       * <code>int64 currentTimeMillis = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbGetServerTimeResp)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbGetServerTimeResp)
    private static final org.game.proto.struct.System.PbGetServerTimeResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.System.PbGetServerTimeResp();
    }

    public static org.game.proto.struct.System.PbGetServerTimeResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbGetServerTimeResp>
        PARSER = new com.google.protobuf.AbstractParser<PbGetServerTimeResp>() {
      @java.lang.Override
      public PbGetServerTimeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbGetServerTimeResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbGetServerTimeResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.System.PbGetServerTimeResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbGetServerTimeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014system.proto\022\025org.game.proto.struct\"0\n" +
      "\023PbGetServerTimeResp\022\031\n\021currentTimeMilli" +
      "s\030\001 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_game_proto_struct_PbGetServerTimeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbGetServerTimeResp_descriptor,
        new java.lang.String[] { "CurrentTimeMillis", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
