// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: task.proto
// Protobuf Java Version: 4.29.0

package org.game.proto.struct;

public final class Task {
  private Task() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Task.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.proto.struct.PbTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int64 progress = 2;</code>
     * @return The progress.
     */
    long getProgress();

    /**
     * <code>bool isFinished = 3;</code>
     * @return The isFinished.
     */
    boolean getIsFinished();

    /**
     * <code>bool isReward = 4;</code>
     * @return The isReward.
     */
    boolean getIsReward();
  }
  /**
   * Protobuf type {@code org.game.proto.struct.PbTask}
   */
  public static final class PbTask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.game.proto.struct.PbTask)
      PbTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        PbTask.class.getName());
    }
    // Use PbTask.newBuilder() to construct.
    private PbTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbTask() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.proto.struct.Task.internal_static_org_game_proto_struct_PbTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.proto.struct.Task.internal_static_org_game_proto_struct_PbTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.proto.struct.Task.PbTask.class, org.game.proto.struct.Task.PbTask.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private long progress_ = 0L;
    /**
     * <code>int64 progress = 2;</code>
     * @return The progress.
     */
    @java.lang.Override
    public long getProgress() {
      return progress_;
    }

    public static final int ISFINISHED_FIELD_NUMBER = 3;
    private boolean isFinished_ = false;
    /**
     * <code>bool isFinished = 3;</code>
     * @return The isFinished.
     */
    @java.lang.Override
    public boolean getIsFinished() {
      return isFinished_;
    }

    public static final int ISREWARD_FIELD_NUMBER = 4;
    private boolean isReward_ = false;
    /**
     * <code>bool isReward = 4;</code>
     * @return The isReward.
     */
    @java.lang.Override
    public boolean getIsReward() {
      return isReward_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (progress_ != 0L) {
        output.writeInt64(2, progress_);
      }
      if (isFinished_ != false) {
        output.writeBool(3, isFinished_);
      }
      if (isReward_ != false) {
        output.writeBool(4, isReward_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (progress_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, progress_);
      }
      if (isFinished_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFinished_);
      }
      if (isReward_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.proto.struct.Task.PbTask)) {
        return super.equals(obj);
      }
      org.game.proto.struct.Task.PbTask other = (org.game.proto.struct.Task.PbTask) obj;

      if (getId()
          != other.getId()) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (getIsFinished()
          != other.getIsFinished()) return false;
      if (getIsReward()
          != other.getIsReward()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProgress());
      hash = (37 * hash) + ISFINISHED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinished());
      hash = (37 * hash) + ISREWARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsReward());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.proto.struct.Task.PbTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.game.proto.struct.Task.PbTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.game.proto.struct.Task.PbTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.proto.struct.Task.PbTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.proto.struct.PbTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.proto.struct.PbTask)
        org.game.proto.struct.Task.PbTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.proto.struct.Task.internal_static_org_game_proto_struct_PbTask_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.proto.struct.Task.internal_static_org_game_proto_struct_PbTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.proto.struct.Task.PbTask.class, org.game.proto.struct.Task.PbTask.Builder.class);
      }

      // Construct using org.game.proto.struct.Task.PbTask.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        progress_ = 0L;
        isFinished_ = false;
        isReward_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.proto.struct.Task.internal_static_org_game_proto_struct_PbTask_descriptor;
      }

      @java.lang.Override
      public org.game.proto.struct.Task.PbTask getDefaultInstanceForType() {
        return org.game.proto.struct.Task.PbTask.getDefaultInstance();
      }

      @java.lang.Override
      public org.game.proto.struct.Task.PbTask build() {
        org.game.proto.struct.Task.PbTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.game.proto.struct.Task.PbTask buildPartial() {
        org.game.proto.struct.Task.PbTask result = new org.game.proto.struct.Task.PbTask(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.game.proto.struct.Task.PbTask result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.progress_ = progress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isFinished_ = isFinished_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isReward_ = isReward_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.proto.struct.Task.PbTask) {
          return mergeFrom((org.game.proto.struct.Task.PbTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.proto.struct.Task.PbTask other) {
        if (other == org.game.proto.struct.Task.PbTask.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getProgress() != 0L) {
          setProgress(other.getProgress());
        }
        if (other.getIsFinished() != false) {
          setIsFinished(other.getIsFinished());
        }
        if (other.getIsReward() != false) {
          setIsReward(other.getIsReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                progress_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                isFinished_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                isReward_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private long progress_ ;
      /**
       * <code>int64 progress = 2;</code>
       * @return The progress.
       */
      @java.lang.Override
      public long getProgress() {
        return progress_;
      }
      /**
       * <code>int64 progress = 2;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(long value) {

        progress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 progress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0L;
        onChanged();
        return this;
      }

      private boolean isFinished_ ;
      /**
       * <code>bool isFinished = 3;</code>
       * @return The isFinished.
       */
      @java.lang.Override
      public boolean getIsFinished() {
        return isFinished_;
      }
      /**
       * <code>bool isFinished = 3;</code>
       * @param value The isFinished to set.
       * @return This builder for chaining.
       */
      public Builder setIsFinished(boolean value) {

        isFinished_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFinished = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFinished() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isFinished_ = false;
        onChanged();
        return this;
      }

      private boolean isReward_ ;
      /**
       * <code>bool isReward = 4;</code>
       * @return The isReward.
       */
      @java.lang.Override
      public boolean getIsReward() {
        return isReward_;
      }
      /**
       * <code>bool isReward = 4;</code>
       * @param value The isReward to set.
       * @return This builder for chaining.
       */
      public Builder setIsReward(boolean value) {

        isReward_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool isReward = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsReward() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isReward_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.proto.struct.PbTask)
    }

    // @@protoc_insertion_point(class_scope:org.game.proto.struct.PbTask)
    private static final org.game.proto.struct.Task.PbTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.proto.struct.Task.PbTask();
    }

    public static org.game.proto.struct.Task.PbTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbTask>
        PARSER = new com.google.protobuf.AbstractParser<PbTask>() {
      @java.lang.Override
      public PbTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbTask> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.game.proto.struct.Task.PbTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_proto_struct_PbTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_proto_struct_PbTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntask.proto\022\025org.game.proto.struct\"L\n\006P" +
      "bTask\022\n\n\002id\030\001 \001(\005\022\020\n\010progress\030\002 \001(\003\022\022\n\ni" +
      "sFinished\030\003 \001(\010\022\020\n\010isReward\030\004 \001(\010b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_game_proto_struct_PbTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_game_proto_struct_PbTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_game_proto_struct_PbTask_descriptor,
        new java.lang.String[] { "Id", "Progress", "IsFinished", "IsReward", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
