spring:
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    config:
      url: jdbc:mysql://localhost:3306/game_config?useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://localhost:3306/game_config?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        max-lifetime: 1800000
        minimum-idle: 0
        idle-timeout: 600000
        maximum-pool-size: 10
        auto-commit: true
        connection-timeout: 30000
        connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

config:
  check: true
  xlsx-path: D:\project\sohoo\Table