spring:
  main:
    banner-mode: off
  data:
    redis:
      repositories:
        enabled: false
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          clientName: null
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 5
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/game?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      minimum-idle: 10
      idle-timeout: 600000
      maximum-pool-size: 50
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: false
        javax:
          cache:
            uri: ehcache.xml
            missing_cache_strategy: fail
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        enable_lazy_load_no_trans: true
        transaction:
          jta:
            platform: org.springframework.orm.jpa.JpaTransactionManager
zookeeper:
  address: localhost:2181
  session-timeout: 30000
  connection-timeout: 5000
  root-path: /logic
logic:
  server-id: 1
  host: localhost
  tcp-port: 11001
  rpc-port: 11002
server:
  port: 11000

config:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/game_config?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      minimum-idle: 0
      idle-timeout: 600000
      maximum-pool-size: 1
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1