services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=0
    restart: always
  redis:
    image: redis:8.0.3
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  zookeeper:
    image: zookeeper:3.9.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always