version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.9.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
  redis:
    image: redis:7.4.2
    container_name: redis
    volumes:
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  mongo:
    image: mongo:8.0.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wangyefeng@19920124
    ports:
      - "27017:27017"
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: WangTang@19920124
    ports:
      - "3306:3306"
    restart: always
  game-login:
    image: game-login:latest
    container_name: game-login
    volumes:
      - /home/game/login/logs/:/app/logs/
      - /home/game/login/hotfix/:/app/hotfix/
    environment:
      TZ: Asia/Shanghai
    restart: always
    depends_on:
      - redis
      - mongo
      - mysql
      - zookeeper
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/client/:/usr/share/nginx/client/
    ports:
      - "80:80"
    restart: always
    depends_on:
      - game-login