services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=0
    restart: always
    networks:
      - my-net
  redis:
    image: redis:8.0.3
    container_name: redis
    volumes:
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - my-net
  zookeeper:
    image: zookeeper:3.9.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    networks:
      - my-net
networks:
  my-net:
    driver: bridge