spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      minimum-idle: 16
      idle-timeout: 600000
      maximum-pool-size: 16
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      repositories:
        enabled: false
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          clientName: null
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 5
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.orm.jpa.JpaTransactionManager
    repositories:
      enabled: true
server:
  port: 10000
  tomcat:
    accept-count: 10000
    threads:
      min-spare: 16
      max: 100
management:
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
