server:
  tcp-port: 12000
  websocket-port: 12001
  ssl:
    enabled: false
    certificate: classpath:ssl/fullchain.pem
    certificate-private-key: classpath:ssl/privkey.pem
spring:
  main:
    banner-mode: off
  data:
    redis:
      repositories:
        enabled: false
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://192.168.101.208:6379"
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          clientName: null
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 5
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
zookeeper:
  address: wangyefeng.top:2181
  session-timeout: 10000
  connection-timeout: 5000
  root-path: logic