// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package org.wyf.game.proto.struct;

@com.google.protobuf.Generated
public final class Common extends com.google.protobuf.GeneratedFile {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Common.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbIntArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbIntArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 val = 1;</code>
     * @return A list containing the val.
     */
    java.util.List<java.lang.Integer> getValList();
    /**
     * <code>repeated int32 val = 1;</code>
     * @return The count of val.
     */
    int getValCount();
    /**
     * <code>repeated int32 val = 1;</code>
     * @param index The index of the element to return.
     * @return The val at the given index.
     */
    int getVal(int index);
  }
  /**
   * Protobuf type {@code PbIntArray}
   */
  public static final class PbIntArray extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PbIntArray)
      PbIntArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        PbIntArray.class.getName());
    }
    // Use PbIntArray.newBuilder() to construct.
    private PbIntArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbIntArray() {
      val_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wyf.game.proto.struct.Common.internal_static_PbIntArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wyf.game.proto.struct.Common.internal_static_PbIntArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wyf.game.proto.struct.Common.PbIntArray.class, org.wyf.game.proto.struct.Common.PbIntArray.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList val_ =
        emptyIntList();
    /**
     * <code>repeated int32 val = 1;</code>
     * @return A list containing the val.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getValList() {
      return val_;
    }
    /**
     * <code>repeated int32 val = 1;</code>
     * @return The count of val.
     */
    public int getValCount() {
      return val_.size();
    }
    /**
     * <code>repeated int32 val = 1;</code>
     * @param index The index of the element to return.
     * @return The val at the given index.
     */
    public int getVal(int index) {
      return val_.getInt(index);
    }
    private int valMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(valMemoizedSerializedSize);
      }
      for (int i = 0; i < val_.size(); i++) {
        output.writeInt32NoTag(val_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < val_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(val_.getInt(i));
        }
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wyf.game.proto.struct.Common.PbIntArray)) {
        return super.equals(obj);
      }
      org.wyf.game.proto.struct.Common.PbIntArray other = (org.wyf.game.proto.struct.Common.PbIntArray) obj;

      if (!getValList()
          .equals(other.getValList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValCount() > 0) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getValList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wyf.game.proto.struct.Common.PbIntArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wyf.game.proto.struct.Common.PbIntArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Common.PbIntArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wyf.game.proto.struct.Common.PbIntArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PbIntArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbIntArray)
        org.wyf.game.proto.struct.Common.PbIntArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wyf.game.proto.struct.Common.internal_static_PbIntArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wyf.game.proto.struct.Common.internal_static_PbIntArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wyf.game.proto.struct.Common.PbIntArray.class, org.wyf.game.proto.struct.Common.PbIntArray.Builder.class);
      }

      // Construct using org.wyf.game.proto.struct.Common.PbIntArray.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        val_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wyf.game.proto.struct.Common.internal_static_PbIntArray_descriptor;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Common.PbIntArray getDefaultInstanceForType() {
        return org.wyf.game.proto.struct.Common.PbIntArray.getDefaultInstance();
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Common.PbIntArray build() {
        org.wyf.game.proto.struct.Common.PbIntArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Common.PbIntArray buildPartial() {
        org.wyf.game.proto.struct.Common.PbIntArray result = new org.wyf.game.proto.struct.Common.PbIntArray(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wyf.game.proto.struct.Common.PbIntArray result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          val_.makeImmutable();
          result.val_ = val_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wyf.game.proto.struct.Common.PbIntArray) {
          return mergeFrom((org.wyf.game.proto.struct.Common.PbIntArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wyf.game.proto.struct.Common.PbIntArray other) {
        if (other == org.wyf.game.proto.struct.Common.PbIntArray.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (val_.isEmpty()) {
            val_ = other.val_;
            val_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureValIsMutable();
            val_.addAll(other.val_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureValIsMutable();
                val_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureValIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  val_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList val_ = emptyIntList();
      private void ensureValIsMutable() {
        if (!val_.isModifiable()) {
          val_ = makeMutableCopy(val_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @return A list containing the val.
       */
      public java.util.List<java.lang.Integer>
          getValList() {
        val_.makeImmutable();
        return val_;
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @return The count of val.
       */
      public int getValCount() {
        return val_.size();
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @param index The index of the element to return.
       * @return The val at the given index.
       */
      public int getVal(int index) {
        return val_.getInt(index);
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @param index The index to set the value at.
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(
          int index, int value) {

        ensureValIsMutable();
        val_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @param value The val to add.
       * @return This builder for chaining.
       */
      public Builder addVal(int value) {

        ensureValIsMutable();
        val_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @param values The val to add.
       * @return This builder for chaining.
       */
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureValIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, val_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        val_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PbIntArray)
    }

    // @@protoc_insertion_point(class_scope:PbIntArray)
    private static final org.wyf.game.proto.struct.Common.PbIntArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wyf.game.proto.struct.Common.PbIntArray();
    }

    public static org.wyf.game.proto.struct.Common.PbIntArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbIntArray>
        PARSER = new com.google.protobuf.AbstractParser<PbIntArray>() {
      @java.lang.Override
      public PbIntArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbIntArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbIntArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wyf.game.proto.struct.Common.PbIntArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbIntArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PbIntArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"\031\n\nPbIntArray\022\013\n\003val\030\001 \003(" +
      "\005B\033\n\031org.wyf.game.proto.structb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PbIntArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbIntArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PbIntArray_descriptor,
        new java.lang.String[] { "Val", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
