// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc.proto
// Protobuf Java Version: 4.32.1

package org.wyf.game.proto.struct;

@com.google.protobuf.Generated
public final class Rpc extends com.google.protobuf.GeneratedFile {
  private Rpc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Rpc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbPlayerExistReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbPlayerExistReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * <pre>
   * 玩家是否存在请求
   * </pre>
   *
   * Protobuf type {@code PbPlayerExistReq}
   */
  public static final class PbPlayerExistReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PbPlayerExistReq)
      PbPlayerExistReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        PbPlayerExistReq.class.getName());
    }
    // Use PbPlayerExistReq.newBuilder() to construct.
    private PbPlayerExistReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbPlayerExistReq() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.class, org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wyf.game.proto.struct.Rpc.PbPlayerExistReq)) {
        return super.equals(obj);
      }
      org.wyf.game.proto.struct.Rpc.PbPlayerExistReq other = (org.wyf.game.proto.struct.Rpc.PbPlayerExistReq) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wyf.game.proto.struct.Rpc.PbPlayerExistReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家是否存在请求
     * </pre>
     *
     * Protobuf type {@code PbPlayerExistReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbPlayerExistReq)
        org.wyf.game.proto.struct.Rpc.PbPlayerExistReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.class, org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.Builder.class);
      }

      // Construct using org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistReq_descriptor;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistReq getDefaultInstanceForType() {
        return org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.getDefaultInstance();
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistReq build() {
        org.wyf.game.proto.struct.Rpc.PbPlayerExistReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistReq buildPartial() {
        org.wyf.game.proto.struct.Rpc.PbPlayerExistReq result = new org.wyf.game.proto.struct.Rpc.PbPlayerExistReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wyf.game.proto.struct.Rpc.PbPlayerExistReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wyf.game.proto.struct.Rpc.PbPlayerExistReq) {
          return mergeFrom((org.wyf.game.proto.struct.Rpc.PbPlayerExistReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wyf.game.proto.struct.Rpc.PbPlayerExistReq other) {
        if (other == org.wyf.game.proto.struct.Rpc.PbPlayerExistReq.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PbPlayerExistReq)
    }

    // @@protoc_insertion_point(class_scope:PbPlayerExistReq)
    private static final org.wyf.game.proto.struct.Rpc.PbPlayerExistReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wyf.game.proto.struct.Rpc.PbPlayerExistReq();
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbPlayerExistReq>
        PARSER = new com.google.protobuf.AbstractParser<PbPlayerExistReq>() {
      @java.lang.Override
      public PbPlayerExistReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbPlayerExistReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbPlayerExistReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wyf.game.proto.struct.Rpc.PbPlayerExistReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbPlayerExistRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbPlayerExistResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool exist = 1;</code>
     * @return The exist.
     */
    boolean getExist();
  }
  /**
   * <pre>
   * 玩家是否存在返回
   * </pre>
   *
   * Protobuf type {@code PbPlayerExistResp}
   */
  public static final class PbPlayerExistResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PbPlayerExistResp)
      PbPlayerExistRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        PbPlayerExistResp.class.getName());
    }
    // Use PbPlayerExistResp.newBuilder() to construct.
    private PbPlayerExistResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbPlayerExistResp() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.class, org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.Builder.class);
    }

    public static final int EXIST_FIELD_NUMBER = 1;
    private boolean exist_ = false;
    /**
     * <code>bool exist = 1;</code>
     * @return The exist.
     */
    @java.lang.Override
    public boolean getExist() {
      return exist_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (exist_ != false) {
        output.writeBool(1, exist_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (exist_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, exist_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wyf.game.proto.struct.Rpc.PbPlayerExistResp)) {
        return super.equals(obj);
      }
      org.wyf.game.proto.struct.Rpc.PbPlayerExistResp other = (org.wyf.game.proto.struct.Rpc.PbPlayerExistResp) obj;

      if (getExist()
          != other.getExist()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExist());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wyf.game.proto.struct.Rpc.PbPlayerExistResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家是否存在返回
     * </pre>
     *
     * Protobuf type {@code PbPlayerExistResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbPlayerExistResp)
        org.wyf.game.proto.struct.Rpc.PbPlayerExistRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.class, org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.Builder.class);
      }

      // Construct using org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        exist_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wyf.game.proto.struct.Rpc.internal_static_PbPlayerExistResp_descriptor;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistResp getDefaultInstanceForType() {
        return org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.getDefaultInstance();
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistResp build() {
        org.wyf.game.proto.struct.Rpc.PbPlayerExistResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Rpc.PbPlayerExistResp buildPartial() {
        org.wyf.game.proto.struct.Rpc.PbPlayerExistResp result = new org.wyf.game.proto.struct.Rpc.PbPlayerExistResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wyf.game.proto.struct.Rpc.PbPlayerExistResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.exist_ = exist_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wyf.game.proto.struct.Rpc.PbPlayerExistResp) {
          return mergeFrom((org.wyf.game.proto.struct.Rpc.PbPlayerExistResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wyf.game.proto.struct.Rpc.PbPlayerExistResp other) {
        if (other == org.wyf.game.proto.struct.Rpc.PbPlayerExistResp.getDefaultInstance()) return this;
        if (other.getExist() != false) {
          setExist(other.getExist());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                exist_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean exist_ ;
      /**
       * <code>bool exist = 1;</code>
       * @return The exist.
       */
      @java.lang.Override
      public boolean getExist() {
        return exist_;
      }
      /**
       * <code>bool exist = 1;</code>
       * @param value The exist to set.
       * @return This builder for chaining.
       */
      public Builder setExist(boolean value) {

        exist_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool exist = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExist() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exist_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PbPlayerExistResp)
    }

    // @@protoc_insertion_point(class_scope:PbPlayerExistResp)
    private static final org.wyf.game.proto.struct.Rpc.PbPlayerExistResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wyf.game.proto.struct.Rpc.PbPlayerExistResp();
    }

    public static org.wyf.game.proto.struct.Rpc.PbPlayerExistResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbPlayerExistResp>
        PARSER = new com.google.protobuf.AbstractParser<PbPlayerExistResp>() {
      @java.lang.Override
      public PbPlayerExistResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbPlayerExistResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbPlayerExistResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wyf.game.proto.struct.Rpc.PbPlayerExistResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbPlayerExistReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PbPlayerExistReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbPlayerExistResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PbPlayerExistResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\"\036\n\020PbPlayerExistReq\022\n\n\002id\030\001 " +
      "\001(\005\"\"\n\021PbPlayerExistResp\022\r\n\005exist\030\001 \001(\0102" +
      "E\n\022PlayerExistService\022/\n\006exists\022\021.PbPlay" +
      "erExistReq\032\022.PbPlayerExistRespB\033\n\031org.wy" +
      "f.game.proto.structb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PbPlayerExistReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbPlayerExistReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PbPlayerExistReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PbPlayerExistResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PbPlayerExistResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PbPlayerExistResp_descriptor,
        new java.lang.String[] { "Exist", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
