// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: task.proto
// Protobuf Java Version: 4.32.1

package org.wyf.game.proto.struct;

@com.google.protobuf.Generated
public final class Task extends com.google.protobuf.GeneratedFile {
  private Task() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Task.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int64 progress = 2;</code>
     * @return The progress.
     */
    long getProgress();

    /**
     * <code>bool isFinished = 3;</code>
     * @return The isFinished.
     */
    boolean getIsFinished();

    /**
     * <code>bool isReward = 4;</code>
     * @return The isReward.
     */
    boolean getIsReward();
  }
  /**
   * Protobuf type {@code PbTask}
   */
  public static final class PbTask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PbTask)
      PbTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        PbTask.class.getName());
    }
    // Use PbTask.newBuilder() to construct.
    private PbTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbTask() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wyf.game.proto.struct.Task.internal_static_PbTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wyf.game.proto.struct.Task.internal_static_PbTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wyf.game.proto.struct.Task.PbTask.class, org.wyf.game.proto.struct.Task.PbTask.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private long progress_ = 0L;
    /**
     * <code>int64 progress = 2;</code>
     * @return The progress.
     */
    @java.lang.Override
    public long getProgress() {
      return progress_;
    }

    public static final int ISFINISHED_FIELD_NUMBER = 3;
    private boolean isFinished_ = false;
    /**
     * <code>bool isFinished = 3;</code>
     * @return The isFinished.
     */
    @java.lang.Override
    public boolean getIsFinished() {
      return isFinished_;
    }

    public static final int ISREWARD_FIELD_NUMBER = 4;
    private boolean isReward_ = false;
    /**
     * <code>bool isReward = 4;</code>
     * @return The isReward.
     */
    @java.lang.Override
    public boolean getIsReward() {
      return isReward_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (progress_ != 0L) {
        output.writeInt64(2, progress_);
      }
      if (isFinished_ != false) {
        output.writeBool(3, isFinished_);
      }
      if (isReward_ != false) {
        output.writeBool(4, isReward_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (progress_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, progress_);
      }
      if (isFinished_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFinished_);
      }
      if (isReward_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wyf.game.proto.struct.Task.PbTask)) {
        return super.equals(obj);
      }
      org.wyf.game.proto.struct.Task.PbTask other = (org.wyf.game.proto.struct.Task.PbTask) obj;

      if (getId()
          != other.getId()) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (getIsFinished()
          != other.getIsFinished()) return false;
      if (getIsReward()
          != other.getIsReward()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProgress());
      hash = (37 * hash) + ISFINISHED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinished());
      hash = (37 * hash) + ISREWARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsReward());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wyf.game.proto.struct.Task.PbTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wyf.game.proto.struct.Task.PbTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Task.PbTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wyf.game.proto.struct.Task.PbTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PbTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbTask)
        org.wyf.game.proto.struct.Task.PbTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTask_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wyf.game.proto.struct.Task.PbTask.class, org.wyf.game.proto.struct.Task.PbTask.Builder.class);
      }

      // Construct using org.wyf.game.proto.struct.Task.PbTask.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        progress_ = 0L;
        isFinished_ = false;
        isReward_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTask_descriptor;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTask getDefaultInstanceForType() {
        return org.wyf.game.proto.struct.Task.PbTask.getDefaultInstance();
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTask build() {
        org.wyf.game.proto.struct.Task.PbTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTask buildPartial() {
        org.wyf.game.proto.struct.Task.PbTask result = new org.wyf.game.proto.struct.Task.PbTask(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wyf.game.proto.struct.Task.PbTask result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.progress_ = progress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isFinished_ = isFinished_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isReward_ = isReward_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wyf.game.proto.struct.Task.PbTask) {
          return mergeFrom((org.wyf.game.proto.struct.Task.PbTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wyf.game.proto.struct.Task.PbTask other) {
        if (other == org.wyf.game.proto.struct.Task.PbTask.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getProgress() != 0L) {
          setProgress(other.getProgress());
        }
        if (other.getIsFinished() != false) {
          setIsFinished(other.getIsFinished());
        }
        if (other.getIsReward() != false) {
          setIsReward(other.getIsReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                progress_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                isFinished_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                isReward_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private long progress_ ;
      /**
       * <code>int64 progress = 2;</code>
       * @return The progress.
       */
      @java.lang.Override
      public long getProgress() {
        return progress_;
      }
      /**
       * <code>int64 progress = 2;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(long value) {

        progress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 progress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0L;
        onChanged();
        return this;
      }

      private boolean isFinished_ ;
      /**
       * <code>bool isFinished = 3;</code>
       * @return The isFinished.
       */
      @java.lang.Override
      public boolean getIsFinished() {
        return isFinished_;
      }
      /**
       * <code>bool isFinished = 3;</code>
       * @param value The isFinished to set.
       * @return This builder for chaining.
       */
      public Builder setIsFinished(boolean value) {

        isFinished_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFinished = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFinished() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isFinished_ = false;
        onChanged();
        return this;
      }

      private boolean isReward_ ;
      /**
       * <code>bool isReward = 4;</code>
       * @return The isReward.
       */
      @java.lang.Override
      public boolean getIsReward() {
        return isReward_;
      }
      /**
       * <code>bool isReward = 4;</code>
       * @param value The isReward to set.
       * @return This builder for chaining.
       */
      public Builder setIsReward(boolean value) {

        isReward_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool isReward = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsReward() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isReward_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PbTask)
    }

    // @@protoc_insertion_point(class_scope:PbTask)
    private static final org.wyf.game.proto.struct.Task.PbTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wyf.game.proto.struct.Task.PbTask();
    }

    public static org.wyf.game.proto.struct.Task.PbTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbTask>
        PARSER = new com.google.protobuf.AbstractParser<PbTask>() {
      @java.lang.Override
      public PbTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbTask> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wyf.game.proto.struct.Task.PbTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbTaskArraysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbTaskArrays)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    java.util.List<org.wyf.game.proto.struct.Task.PbTask> 
        getTasksList();
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    org.wyf.game.proto.struct.Task.PbTask getTasks(int index);
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    int getTasksCount();
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    java.util.List<? extends org.wyf.game.proto.struct.Task.PbTaskOrBuilder> 
        getTasksOrBuilderList();
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    org.wyf.game.proto.struct.Task.PbTaskOrBuilder getTasksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PbTaskArrays}
   */
  public static final class PbTaskArrays extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PbTaskArrays)
      PbTaskArraysOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        PbTaskArrays.class.getName());
    }
    // Use PbTaskArrays.newBuilder() to construct.
    private PbTaskArrays(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PbTaskArrays() {
      tasks_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wyf.game.proto.struct.Task.internal_static_PbTaskArrays_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wyf.game.proto.struct.Task.internal_static_PbTaskArrays_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wyf.game.proto.struct.Task.PbTaskArrays.class, org.wyf.game.proto.struct.Task.PbTaskArrays.Builder.class);
    }

    public static final int TASKS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.wyf.game.proto.struct.Task.PbTask> tasks_;
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.wyf.game.proto.struct.Task.PbTask> getTasksList() {
      return tasks_;
    }
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.wyf.game.proto.struct.Task.PbTaskOrBuilder> 
        getTasksOrBuilderList() {
      return tasks_;
    }
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    @java.lang.Override
    public int getTasksCount() {
      return tasks_.size();
    }
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    @java.lang.Override
    public org.wyf.game.proto.struct.Task.PbTask getTasks(int index) {
      return tasks_.get(index);
    }
    /**
     * <code>repeated .PbTask tasks = 1;</code>
     */
    @java.lang.Override
    public org.wyf.game.proto.struct.Task.PbTaskOrBuilder getTasksOrBuilder(
        int index) {
      return tasks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tasks_.size(); i++) {
        output.writeMessage(1, tasks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tasks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wyf.game.proto.struct.Task.PbTaskArrays)) {
        return super.equals(obj);
      }
      org.wyf.game.proto.struct.Task.PbTaskArrays other = (org.wyf.game.proto.struct.Task.PbTaskArrays) obj;

      if (!getTasksList()
          .equals(other.getTasksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTasksCount() > 0) {
        hash = (37 * hash) + TASKS_FIELD_NUMBER;
        hash = (53 * hash) + getTasksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.wyf.game.proto.struct.Task.PbTaskArrays parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wyf.game.proto.struct.Task.PbTaskArrays prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PbTaskArrays}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbTaskArrays)
        org.wyf.game.proto.struct.Task.PbTaskArraysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTaskArrays_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTaskArrays_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wyf.game.proto.struct.Task.PbTaskArrays.class, org.wyf.game.proto.struct.Task.PbTaskArrays.Builder.class);
      }

      // Construct using org.wyf.game.proto.struct.Task.PbTaskArrays.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
        } else {
          tasks_ = null;
          tasksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wyf.game.proto.struct.Task.internal_static_PbTaskArrays_descriptor;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTaskArrays getDefaultInstanceForType() {
        return org.wyf.game.proto.struct.Task.PbTaskArrays.getDefaultInstance();
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTaskArrays build() {
        org.wyf.game.proto.struct.Task.PbTaskArrays result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wyf.game.proto.struct.Task.PbTaskArrays buildPartial() {
        org.wyf.game.proto.struct.Task.PbTaskArrays result = new org.wyf.game.proto.struct.Task.PbTaskArrays(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.wyf.game.proto.struct.Task.PbTaskArrays result) {
        if (tasksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tasks_ = java.util.Collections.unmodifiableList(tasks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tasks_ = tasks_;
        } else {
          result.tasks_ = tasksBuilder_.build();
        }
      }

      private void buildPartial0(org.wyf.game.proto.struct.Task.PbTaskArrays result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wyf.game.proto.struct.Task.PbTaskArrays) {
          return mergeFrom((org.wyf.game.proto.struct.Task.PbTaskArrays)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wyf.game.proto.struct.Task.PbTaskArrays other) {
        if (other == org.wyf.game.proto.struct.Task.PbTaskArrays.getDefaultInstance()) return this;
        if (tasksBuilder_ == null) {
          if (!other.tasks_.isEmpty()) {
            if (tasks_.isEmpty()) {
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTasksIsMutable();
              tasks_.addAll(other.tasks_);
            }
            onChanged();
          }
        } else {
          if (!other.tasks_.isEmpty()) {
            if (tasksBuilder_.isEmpty()) {
              tasksBuilder_.dispose();
              tasksBuilder_ = null;
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tasksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetTasksFieldBuilder() : null;
            } else {
              tasksBuilder_.addAllMessages(other.tasks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.wyf.game.proto.struct.Task.PbTask m =
                    input.readMessage(
                        org.wyf.game.proto.struct.Task.PbTask.parser(),
                        extensionRegistry);
                if (tasksBuilder_ == null) {
                  ensureTasksIsMutable();
                  tasks_.add(m);
                } else {
                  tasksBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.wyf.game.proto.struct.Task.PbTask> tasks_ =
        java.util.Collections.emptyList();
      private void ensureTasksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tasks_ = new java.util.ArrayList<org.wyf.game.proto.struct.Task.PbTask>(tasks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.wyf.game.proto.struct.Task.PbTask, org.wyf.game.proto.struct.Task.PbTask.Builder, org.wyf.game.proto.struct.Task.PbTaskOrBuilder> tasksBuilder_;

      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public java.util.List<org.wyf.game.proto.struct.Task.PbTask> getTasksList() {
        if (tasksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tasks_);
        } else {
          return tasksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public int getTasksCount() {
        if (tasksBuilder_ == null) {
          return tasks_.size();
        } else {
          return tasksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public org.wyf.game.proto.struct.Task.PbTask getTasks(int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);
        } else {
          return tasksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder setTasks(
          int index, org.wyf.game.proto.struct.Task.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.set(index, value);
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder setTasks(
          int index, org.wyf.game.proto.struct.Task.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.set(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder addTasks(org.wyf.game.proto.struct.Task.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder addTasks(
          int index, org.wyf.game.proto.struct.Task.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(index, value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder addTasks(
          org.wyf.game.proto.struct.Task.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder addTasks(
          int index, org.wyf.game.proto.struct.Task.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder addAllTasks(
          java.lang.Iterable<? extends org.wyf.game.proto.struct.Task.PbTask> values) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tasks_);
          onChanged();
        } else {
          tasksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder clearTasks() {
        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tasksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public Builder removeTasks(int index) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.remove(index);
          onChanged();
        } else {
          tasksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public org.wyf.game.proto.struct.Task.PbTask.Builder getTasksBuilder(
          int index) {
        return internalGetTasksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public org.wyf.game.proto.struct.Task.PbTaskOrBuilder getTasksOrBuilder(
          int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);  } else {
          return tasksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public java.util.List<? extends org.wyf.game.proto.struct.Task.PbTaskOrBuilder> 
           getTasksOrBuilderList() {
        if (tasksBuilder_ != null) {
          return tasksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tasks_);
        }
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public org.wyf.game.proto.struct.Task.PbTask.Builder addTasksBuilder() {
        return internalGetTasksFieldBuilder().addBuilder(
            org.wyf.game.proto.struct.Task.PbTask.getDefaultInstance());
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public org.wyf.game.proto.struct.Task.PbTask.Builder addTasksBuilder(
          int index) {
        return internalGetTasksFieldBuilder().addBuilder(
            index, org.wyf.game.proto.struct.Task.PbTask.getDefaultInstance());
      }
      /**
       * <code>repeated .PbTask tasks = 1;</code>
       */
      public java.util.List<org.wyf.game.proto.struct.Task.PbTask.Builder> 
           getTasksBuilderList() {
        return internalGetTasksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.wyf.game.proto.struct.Task.PbTask, org.wyf.game.proto.struct.Task.PbTask.Builder, org.wyf.game.proto.struct.Task.PbTaskOrBuilder> 
          internalGetTasksFieldBuilder() {
        if (tasksBuilder_ == null) {
          tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.wyf.game.proto.struct.Task.PbTask, org.wyf.game.proto.struct.Task.PbTask.Builder, org.wyf.game.proto.struct.Task.PbTaskOrBuilder>(
                  tasks_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tasks_ = null;
        }
        return tasksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PbTaskArrays)
    }

    // @@protoc_insertion_point(class_scope:PbTaskArrays)
    private static final org.wyf.game.proto.struct.Task.PbTaskArrays DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wyf.game.proto.struct.Task.PbTaskArrays();
    }

    public static org.wyf.game.proto.struct.Task.PbTaskArrays getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbTaskArrays>
        PARSER = new com.google.protobuf.AbstractParser<PbTaskArrays>() {
      @java.lang.Override
      public PbTaskArrays parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PbTaskArrays> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbTaskArrays> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wyf.game.proto.struct.Task.PbTaskArrays getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PbTask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbTaskArrays_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PbTaskArrays_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntask.proto\"L\n\006PbTask\022\n\n\002id\030\001 \001(\005\022\020\n\010pr" +
      "ogress\030\002 \001(\003\022\022\n\nisFinished\030\003 \001(\010\022\020\n\010isRe" +
      "ward\030\004 \001(\010\"&\n\014PbTaskArrays\022\026\n\005tasks\030\001 \003(" +
      "\0132\007.PbTaskB\033\n\031org.wyf.game.proto.structb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PbTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PbTask_descriptor,
        new java.lang.String[] { "Id", "Progress", "IsFinished", "IsReward", });
    internal_static_PbTaskArrays_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PbTaskArrays_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PbTaskArrays_descriptor,
        new java.lang.String[] { "Tasks", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
